# Generated by Django 3.1.3 on 2020-12-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('visitor_num', models.PositiveIntegerField()),
            ],
        ),
    ]
