# Generated by Django 3.1.3 on 2020-12-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_hellovisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiacountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asia_country', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
            ],
        ),
    ]
